version: "3"
services:
  syslog:
    build: ./syslog/.
    container_name: syslog
    image: nullping/syslog:latest
    ports:
      - "0.0.0.0:514:514/udp"
      - "0.0.0.0:601:601"
      - "0.0.0.0:6514:6514"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/ssl-certs/cert.pem:/runtime/syslog/ssl/cert.pem:ro"
      - "/data/ssl-certs/privkey.pem:/runtime/syslog/ssl/privkey.pem:ro"
      - "./runtime:/runtime"
    restart: unless-stopped
    healthcheck:
      disable: 'true'
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet:  172.100.0.1/16
